### ISSUE TITLE
Features for cell subtype calling

### ISSUE THREAD

**Issue by MeyerBender** [sagar87/spatialproteomics#100]
Features to be implemented.

```
# in this case: all of these markers need to be positive
B:
  subtypes:
    - name: B_prol
      markers: ["Ki-67+"]
T:
  subtypes:
    - name: T_exh
      markers: ["PD1+", "Tim3+", "LAG3+"]



# in this case, any of the markers would encode for exhaustion
B:
  subtypes:
    - name: B_prol
      markers: ["Ki-67+"]
T:
  subtypes:
    - name: T_exh
      markers: ["PD1+"]
    - name: T_exh
      markers: ["Tim3+"]
    - name: T_exh
      markers: ["LAG3+"]


# marker negativity
B:
  subtypes:
    - name: B_prol
      markers: ["Ki-67+"]
T:
  subtypes:
    - name: T_h
      markers: ["CD8-"]


# marker positivity AND negativity
B:
  subtypes:
    - name: B_prol
      markers: ["Ki-67+"]
T:
  subtypes:
    - name: T_h
      markers: ["CD8-", "CD4+"]

# modeling double-positive cells
B:
  subtypes:
    - name: B_prol
      markers: ["Ki-67+"]
T:
  subtypes:
    - name: T_double_pos
      markers: ["CD4+", "CD8+"]
    - name: T_h
      markers: ["CD4+"]
    - name: T_tox
      markers: ["CD8+"]
```

Also: store all levels in a different table than obs, that way we do not need to parse from str to int again.
In addition, we want to be able to classify even if some markers aren't binarized, in that case we just go as far down in the tree as we can.
